# Generated by Django 3.1.7 on 2021-02-25 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=255, verbose_name='Название породы')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('breed_description', models.CharField(max_length=255, verbose_name='Описание породы')),
            ],
        ),
        migrations.CreateModel(
            name='FormOfCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_form', models.CharField(max_length=255, verbose_name='Название вида')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('form_description', models.CharField(max_length=255, verbose_name='Описание вида')),
                ('category_form_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.breed', verbose_name='Вид Кошки')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_specification', models.CharField(max_length=255, verbose_name='Спецификация кошки')),
                ('slug', models.SlugField(unique=True)),
                ('lifespan', models.PositiveIntegerField(verbose_name='Продолжительность жизни')),
                ('cat_color', models.CharField(max_length=255, verbose_name='Окрас')),
                ('personality', models.CharField(max_length=255, verbose_name='Характер')),
                ('nutrition', models.CharField(max_length=255, verbose_name='Питание')),
                ('image', models.ImageField(upload_to='')),
                ('category_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.formofcat', verbose_name='Вид Кошки')),
            ],
        ),
    ]
