# Generated by Django 3.1.7 on 2021-02-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.breed', verbose_name='Порода Кошки'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.formofcat', verbose_name='Вид Кошки'),
        ),
    ]
