# Generated by Django 3.1.7 on 2021-03-07 14:29

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210303_0202'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='breed',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='formofcat',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='avatar',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
