# Generated by Django 3.1.7 on 2021-03-07 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210307_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='about',
            field=models.CharField(max_length=255, verbose_name='Коммантарий'),
            preserve_default=False,
        ),
    ]
