# Generated by Django 3.1.7 on 2021-03-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_volunteer_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='photo',
        ),
    ]
