# Generated by Django 3.1.7 on 2021-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_volunteer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='about',
            field=models.CharField(default='', max_length=255, verbose_name='Коммантарий'),
        ),
    ]
