# Generated by Django 3.1.7 on 2021-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210320_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='about',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коммантарий'),
        ),
    ]
