# Generated by Django 3.1.7 on 2021-03-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210320_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
        migrations.AlterModelOptions(
            name='formofcat',
            options={'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
    ]
