# Generated by Django 3.1.7 on 2021-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210320_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='image',
            field=models.ImageField(upload_to='breeds/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cats/'),
        ),
        migrations.AlterField(
            model_name='formofcat',
            name='image',
            field=models.ImageField(upload_to='forms/'),
        ),
    ]
