# Generated by Django 3.1.7 on 2021-04-21 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=255, verbose_name='Название породы')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='breeds/')),
                ('breed_description', models.CharField(max_length=255, verbose_name='Описание породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(blank=True, verbose_name='Коммантарий')),
            ],
            options={
                'verbose_name': 'Волонтёр',
                'verbose_name_plural': 'Волонтёры',
            },
        ),
        migrations.CreateModel(
            name='FormOfCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_form', models.CharField(max_length=255, verbose_name='Название вида')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='forms/')),
                ('form_description', models.CharField(max_length=255, verbose_name='Описание вида')),
                ('category_form_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.breed', verbose_name='Вид Кошки')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('lifespan', models.PositiveIntegerField(verbose_name='Продолжительность жизни')),
                ('cat_color', models.CharField(max_length=255, verbose_name='Окрас')),
                ('personality', models.CharField(max_length=255, verbose_name='Характер')),
                ('nutrition', models.CharField(max_length=255, verbose_name='Питание')),
                ('image', models.ImageField(upload_to='cats/')),
                ('category_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.breed', verbose_name='Порода Кошки')),
                ('name_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.formofcat', verbose_name='Вид Кошки')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
    ]
