# Generated by Django 3.1.7 on 2021-05-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='breed',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='formofcat',
            managers=[
            ],
        ),
    ]
